CREATE TABLE Berufsfachschule (
  ID INT,
  Berufsfachschule VARCHAR(100)
);

INSERT INTO berufsfachschule (ID, Berufsfachschule)
VALUES (1, 'Berufsbildungsschule WInterthur'),
(2, 'Berufsfachschule Technische Berufsschule Zürich'),
(3, 'Berufsbildungsschule WInterthur'),
(4, 'Berufsfachschule Technische Berufsschule Zürich'),
(5, 'Berufsbildungsschule WInterthur'),
(6, 'Berufsfachschule Technische Berufsschule Zürich'),
(7, 'Berufsbildungsschule WInterthur'),
(8, 'Berufsfachschule Technische Berufsschule Zürich'),
(9, 'Berufsbildungsschule WInterthur'),
(10, 'Berufsfachschule Technische Berufsschule Zürich'),
(11, 'Berufsbildungsschule WInterthur'),
(12, 'Berufsfachschule Technische Berufsschule Zürich'),
(13, 'Berufsbildungsschule WInterthur'),
(14, 'Berufsfachschule Technische Berufsschule Zürich'),
(15, 'Berufsbildungsschule WInterthur'),
(16, 'Berufsfachschule Technische Berufsschule Zürich'),
(17, 'Berufsbildungsschule WInterthur'),
(18, 'Berufsfachschule Technische Berufsschule Zürich'),
(19, 'Berufsbildungsschule WInterthur'),
(20, 'Berufsfachschule Technische Berufsschule Zürich'),
(21, 'Berufsfachschule Technische Berufsschule Zürich'),
(22, 'Berufsbildungsschule WInterthur'),
(23, 'Berufsfachschule Technische Berufsschule Zürich'),
(24, 'Berufsbildungsschule WInterthur'),
(25, 'Berufsfachschule Technische Berufsschule Zürich'),
(26, 'Berufsbildungsschule WInterthur'),
(27, 'Berufsfachschule Technische Berufsschule Zürich'),
(28, 'Berufsbildungsschule WInterthur'),
(29, 'Berufsfachschule Technische Berufsschule Zürich'),
(30, 'Berufsbildungsschule WInterthur'),
(31, 'Berufsfachschule Technische Berufsschule Zürich'),
(32, 'Berufsfachschule Technische Berufsschule Zürich'),
(33, 'Berufsbildungsschule WInterthur'),
(34, 'Berufsfachschule Technische Berufsschule Zürich'),
(35, 'Berufsbildungsschule WInterthur'),
(36, 'Berufsfachschule Technische Berufsschule Zürich'),
(37, 'Berufsbildungsschule WInterthur'),
(38, 'Berufsfachschule Technische Berufsschule Zürich'),
(39, 'Berufsbildungsschule WInterthur'),
(40, 'Berufsfachschule Technische Berufsschule Zürich'),
(41, 'Berufsbildungsschule WInterthur'),
(42, 'Berufsfachschule Technische Berufsschule Zürich'),
(43, 'Berufsbildungsschule WInterthur'),
(44, 'Berufsfachschule Technische Berufsschule Zürich'),
(45, 'Berufsbildungsschule WInterthur'),
(46, 'Berufsfachschule Technische Berufsschule Zürich'),
(47, 'Berufsbildungsschule WInterthur'),
(48, 'Berufsfachschule Technische Berufsschule Zürich'),
(49, 'Berufsbildungsschule WInterthur'),
(50, 'Berufsfachschule Technische Berufsschule Zürich'),
(51, 'Berufsfachschule Technische Berufsschule Zürich'),
(52, 'Berufsbildungsschule WInterthur'),
(53, 'Berufsfachschule Technische Berufsschule Zürich'),
(54, 'Berufsbildungsschule WInterthur'),
(55, 'Berufsfachschule Technische Berufsschule Zürich'),
(56, 'Berufsbildungsschule WInterthur'),
(57, 'Berufsfachschule Technische Berufsschule Zürich'),
(58, 'Berufsbildungsschule WInterthur'),
(59, 'Berufsfachschule Technische Berufsschule Zürich'),
(60, 'Berufsbildungsschule WInterthur'),
(61, 'Berufsfachschule Technische Berufsschule Zürich'),
(62, 'Berufsfachschule Technische Berufsschule Zürich'),
(63, 'Berufsbildungsschule WInterthur'),
(64, 'Berufsfachschule Technische Berufsschule Zürich'),
(65, 'Berufsbildungsschule WInterthur'),
(66, 'Berufsfachschule Technische Berufsschule Zürich'),
(67, 'Berufsbildungsschule WInterthur'),
(68, 'Berufsfachschule Technische Berufsschule Zürich'),
(69, 'Berufsbildungsschule WInterthur'),
(70, 'Berufsfachschule Technische Berufsschule Zürich'),
(71, 'Berufsbildungsschule WInterthur'),
(72, 'Berufsfachschule Technische Berufsschule Zürich'),
(73, 'Berufsbildungsschule WInterthur'),
(74, 'Berufsfachschule Technische Berufsschule Zürich'),
(75, 'Berufsfachschule Technische Berufsschule Zürich'),
(76, 'Berufsbildungsschule WInterthur'),
(77, 'Berufsfachschule Technische Berufsschule Zürich'),
(78, 'Berufsbildungsschule WInterthur'),
(79, 'Berufsfachschule Technische Berufsschule Zürich'),
(80, 'Berufsbildungsschule WInterthur'),
(81, 'Berufsfachschule Technische Berufsschule Zürich'),
(82, 'Berufsbildungsschule WInterthur'),
(83, 'Berufsfachschule Technische Berufsschule Zürich'),
(84, 'Berufsbildungsschule WInterthur'),
(85, 'Berufsfachschule Technische Berufsschule Zürich'),
(86, 'Berufsbildungsschule WInterthur'),
(87, 'Berufsfachschule Technische Berufsschule Zürich'),
(88, 'Berufsbildungsschule WInterthur'),
(89, 'Berufsfachschule Technische Berufsschule Zürich'),
(90, 'Berufsbildungsschule WInterthur'),
(91, 'Berufsfachschule Technische Berufsschule Zürich'),
(92, 'Berufsbildungsschule WInterthur'),
(93, 'Berufsfachschule Technische Berufsschule Zürich'),
(94, 'Berufsbildungsschule WInterthur'),
(95, 'Berufsfachschule Technische Berufsschule Zürich'),
(96, 'Berufsbildungsschule WInterthur'),
(97, 'Berufsfachschule Technische Berufsschule Zürich'),
(98, 'Berufsbildungsschule WInterthur'),
(99, 'Berufsfachschule Technische Berufsschule Zürich'),
(100, 'Berufsfachschule Technische Berufsschule Zürich')